on:
  # Note: Using 'pull_request_target' to ensure the token has write permissions for modifying pull requests
  pull_request_target:
    types: [opened, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  request-review:
    if: github.repository == 'projectcontour/helm-charts'
    runs-on: ubuntu-latest
    steps:
      # Security note: Avoid checking out the pull request's code to prevent running untrusted code with 'pull_request_target'.
      - name: Request reviewers
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --repo "${{ github.repository }}" --add-reviewer projectcontour/contour-helm-chart-maintainers
